cassandra.hosts.comma.separated=cassandra
cassandra.port=9042
cassandra.keyspace=tnf
cassandra.user=cassandra
cassandra.password=cassandra
db.user=cassandra
db.password=cassandra
db.cassandra.create.keyspace.cql=CREATE KEYSPACE if not exists tnf WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;
