webserver.port=8009
webserver.https.port=8010
webserver.keystore.file=server-keystore.jks
webserver.keystore.password=server
webserver.key.password=server
webserver.host=0.0.0.0
webserver.thread.pool.size=-1

token.minutes.to.live=480

auth.method=HmacSHA512
auth.secret=asdfasdfasdfasdfasdfasdfa

search.time.filter=true
rest.user.stat=false

cassandra.net.compress=false

find.consistency.level=QUORUM
